[package]
name = "step_1_2"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { version = "1", default-features = false, features = [
  "time",
  "macros",
  "rt-multi-thread",
] }
